# Robot name goes here
flat_drone: # change the name
  # default controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # gazebo_ros_control:
  #   pid_gains:  
  #     arm_joint_1:
  #       p: 1
  #       i: 1
  #       d: 1
  #     arm_joint_2:
  #       p: 1
  #       i: 1
  #       d: 1
  #     arm_joint_3:
  #       p: 1
  #       i: 1
  #       d: 1
  #     left_finger_joint:
  #       p: 1
  #       i: 1
  #       d: 1
  #     right_finger_joint:
  #       p: 1
  #       i: 1
  #       d: 1
      
      
  # # Controller 1
  # arm_body_controller: # change the name
  #   type: velocity_controllers/JointVelocityController # Type of controller. 
  #   joint: arm_joint_1 # Name of the joint.  

  # # Controller 2
  # arm_mid_controller: # change the name
  #   type: velocity_controllers/JointVelocityController # Type of controller. 
  #   joint: arm_joint_2 # Name of the joint.  

  # arm_end_controller: # change the name
  #   type: velocity_controllers/JointVelocityController # Type of controller. 
  #   joint: arm_joint_3 # Name of the joint.  

  # right_finger_controller: # change the name
  #   type: velocity_controllers/JointVelocityController # Type of controller. 
  #   joint: right_finger_joint # Name of the joint.  

  # left_finger_controller: # change the name
  #   type: velocity_controllers/JointVelocityController # Type of controller. 
  #   joint: left_finger_joint # Name of the joint.  